# The URL the site will be built for
base_url = "https://openmsupply.github.io/application-manager-web-app/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "zola_easydocs_theme"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
smart_punctuation = true
external_links_target_blank = true

[extra]
# Put all your custom variables here
logo = "https://msupply.foundation/themes/open-msupply/img/mFlow.svg"
release = "https://github.com/openmsupply/application-manager-web-app/releases/tag/B-1.0.0"
favicon = "https://msupply.foundation/themes/open-msupply/img/mFlow_favicon.ico"