import useGetReviewStructureForSections from './useGetReviewStructureForSection'
import useGetReviewStructureForSectionAsync from './useGetReviewStructureForSectionAsync'

export default useGetReviewStructureForSections
export { useGetReviewStructureForSectionAsync as useGetFullReviewStructureAsync }
