import { Decision } from './generated/graphql'

export default {
  APP_NAME: 'mFlow',
  APP_NAME_SUBHEADER: 'Gerenciador de formulários',
  ACTION_ASSIGN: 'Atribuir',
  ACTION_CONTINUE: 'Continuar',
  ACTION_START: 'Iniciar',
  ACTION_DATE_RE_SUBMITTED: 'Reenviado',
  ACTION_DATE_ASSIGNED: 'Atribuido',
  ACTION_DATE_REVIEW_SUBMITTED: 'Avaliação enviada',
  ACTION_DATE_REVIEW_STARTED: 'Availianção iniciada',
  ACTION_MAKE_DECISION: 'Tomada de decisão',
  ACTION_RE_REVIEW: 'Reavaliar',
  ACTION_RE_ASSIGN: 'Reatribuir',
  ACTION_SELF_ASSIGN: 'Atribuir a mim',
  ACTION_UPDATE: 'Atualizar',
  ACTION_VIEW: 'Visualizar',
  ACTION_MAKE_CHANGES: 'Fazer alterções',
  ACTION_EDIT_DRAFT: 'Editar rascunho',
  OUTCOME_PENDING: 'Em andamento',
  OUTCOME_APPROVED: 'Aprovado',
  OUTCOME_REJECTED: 'Reprovado',
  OUTCOME_EXPIRED: 'Caduco',
  OUTCOME_WITHDRAWN: '',
  STATUS_SUBMITTED: 'Enviado',
  STATUS_DRAFT: 'Rascunho',
  STATUS_CHANGES_REQUIRED: 'Solicitação de mudança',
  STATUS_RE_SUBMITTED: 'Re-enviado',
  STATUS_COMPLETED: 'Completo',
  ASSIGNED: 'Atribuído',
  ASSIGNED_TO: 'Atribuído a',
  ASSIGNMENT_NOT_ASSIGNED: 'Aguardando atribuição',
  ASSIGNMENT_YOURSELF: 'mim',
  ASSIGNMENT_UNASSIGN: 'Desatribuir',
  COLUMN_SERIAL: 'Identificador',
  COLUMN_LAST_ACTIVE_DATE: 'Última atualização',
  COLUMN_DEADLINE_DATE: 'Prazo',
  COLUMN_APPLICATION: 'Formulário',
  COLUMN_APPLICATION_REVIEW: 'Formulário',
  COLUMN_APPLICANT: 'Solicitante',
  COLUMN_ORGANISATION: 'Organização',
  COLUMN_CONSOLIDATOR: 'Revisor',
  COLUMN_STAGE: 'Fase',
  COLUMN_STATUS: 'Progresso',
  COLUMN_OUTCOME: 'Estatus',
  COLUMN_REVIEWER_ACTION: '',
  COLUMN_APPLICANT_ACTION: '',
  BUTTON_APPLICATION_NEW: 'Novo formulário',
  BUTTON_APPLICATION_RESUME: 'Continuar',
  BUTTON_APPLICATION_START: 'Iniciar',
  BUTTON_APPLICATION_SUBMIT: 'Enviar formulário',
  BUTTON_BACK: 'Voltar',
  BUTTON_BACK_DASHBOARD: 'Voltar a tela inicial',
  BUTTON_CLEAR_SEARCH: 'Limpar busca',
  BUTTON_NEXT: 'Próxima',
  BUTTON_DASHBOARD_NEW: 'Novo',
  BUTTON_DASHBOARD_VIEW_ALL: 'Ver todos',
  BUTTON_PREVIOUS: 'Anterior',
  BUTTON_REVIEW_AGREE_ALL: 'Concordar com todos',
  BUTTON_REVIEW_APPROVE_ALL: 'Aprovar todos',
  BUTTON_REVIEW_RE_REVIEW: 'Reavaliar',
  BUTTON_REVIEW_RESPONSE: 'Availar',
  BUTTON_RE_REVIEW_RESPONSE: 'Reavaliar',
  BUTTON_REVIEW_SUBMIT: 'Enviar avaliação',
  BUTTON_SELF_ASSIGN: 'Atribuir a mim',
  BUTTON_SUMMARY: 'Ver última página',
  BUTTON_SUBMIT: 'Enviar',
  BUTTON_VALIDATING: 'A verificar',
  BUTTON_VIEW_APPLICATION: 'Ver formulário enviado',
  BUTTON_CANCEL: 'Cancelar',
  BUTTON_SUBMIT_APPLICATION: 'Enviar formulário',
  BUTTON_SUMMARY_EDIT: 'Alterar',
  BUTTON_ADD_REVIEW: 'Adicionar availiação',
  BUTTON_VIEW_HISTORY: 'Ver histórico',
  PLACEHOLDER_SEARCH: 'Buscar formulários',
  DATE_APPLICATION_PLACEHOLDER: '',
  ERROR_APPLICATION_CREATE: 'Problema identificado ao carregar página para criar formulário',
  ERROR_APPLICATION_PAGE: 'Problema identificado ao carregar formulário',
  ERROR_APPLICATION_SUBMIT: 'Problema identificado ao enviar formulário',
  ERROR_APPLICATIONS_LIST: 'Problema identificador ao listar formulários',
  ERROR_GENERIC: 'Algo não esperado ocorreu',
  ERROR_REVIEW_PAGE: 'Problema identificado ao carregar avaliação',
  ERROR_LOGIN_PASSWORD: 'Ups! Usuário ou senha inválidos',
  LABEL_APPLICATIONS: 'formulários',
  LABEL_APPLICATION_SUBMITTED: 'Formulários enviados',
  LABEL_APPLICATION_BACK: 'Voltar ao formulário',
  LABEL_APPLICATION_PAGE: 'Página',
  LABEL_ASSIGNED_TO_YOU: 'Atribuído a mim',
  LABEL_ASSIGNED_TO_OTHER: 'Atribuído a outro avaliador',
  LABEL_ASSIGNMENT_LOCKED: 'Bloqueado para',
  LABEL_ASSIGNMENT_SELF: 'A ser atribuído a mim',
  LABEL_ASSIGNMENT_AVAILABLE: 'A ser atribuído para',
  LABEL_COMMENT: 'Adicionar comentário',
  LABEL_CONSOLIDATE: 'Revisar',
  LABEL_CONSOLIDATION_AGREE: 'Concordo',
  LABEL_CONSOLIDATION_DISAGREE: 'Discordo',
  LABEL_CONSOLIDATION_AGREEMENT: 'Em acordo',
  LABEL_CONSOLIDATION_DISAGREEMENT: 'Em desacordo',
  LABEL_DASHBOARD_NO_APPLICATIONS: 'Não existem formulários em progresso',
  LABEL_DASHBOARD_START_NEW: 'Iniciar um novo formuário de %1',
  LABEL_LIST_PER_PAGE: 'Formulários por página',
  LABEL_LOADING: 'A carregar...',
  LABEL_LOGIN_PASSWORD: 'Senha',
  LABEL_LOGIN_USERNAME: 'Usuário',
  LABEL_LOG_IN: 'Logar',
  LABEL_NO_ORG: 'Sem organisação',
  LABEL_NO_ORG_SELECT: 'Sem organisação (agir como usuário apenas)',
  LABEL_NO_ORG_OPTION: 'Logar sem organização',
  LABEL_PROCESSING: 'A seguir...',
  LABEL_PREVIOUS_REVIEW: 'Avaliação anterior',
  LABEL_REVIEW: 'Formulário em progresso',
  LABEL_REVIEW_APPROVE: 'Aprovar',
  LABEL_REVIEW_DECISION: 'Decisão',
  LABEL_REVIEW_APPROVED: 'Aprovado',
  LABEL_REVIEW_DECLINED: 'Não aprovar',
  LABEL_REVIEW_DECICION_CONFORM: 'Aprovado',
  LABEL_REVIEW_DECISION_NON_CONFORM: 'Não aprovado',
  LABEL_REVIEW_IN_PROGRESS: 'Avaiação em andamento',
  LABEL_REVIEW_OVERALL_COMMENT: 'Comentário geral',
  LABEL_REVIEW_RESSUBMIT: 'Não aprovado',
  LABEL_REVIEW_SECTION: 'Favor completar a secção',
  LABEL_REVIEW_SUBMIT_AS: 'Enviar como',
  LABEL_REVIEW_SUBMITTED_AS: 'Enviado como',
  LABEL_REVIEW_REVIEWED_BY: 'Availiado por',
  LABEL_REVIEW_CONSOLIDATION_BY: 'Revisado por',
  LABEL_REVIEWER: 'Avaliador',
  LABEL_RESPONSE_UPDATE: 'Atualizar',
  LABEL_RESPONSE_UPDATED: 'Atualizado',
  LABEL_SECTION_PROBLEM: 'Erros',
  LABEL_SECTION_COMPLETED: 'Completo',
  LABEL_VERIFICATION_FAILED: 'Verificação falhou',
  LINK_LOGIN_USER: 'Criar nova conta',
  MENU_ITEM_DASHBOARD: 'Página inicial',
  MENU_ITEM_APPLICATION_LIST: 'Lista de formulários',
  MENU_ITEM_OUTCOMES: 'Resultados',
  MENU_ITEM_ADMIN_CONFIG: 'Configuração',
  MENU_ITEM_ADMIN_TEMPLATES: 'Formatação/Procedimentos',
  MENU_ITEM_ADMIN_LOOKUP_TABLES: 'Tabelas dinâmicas',
  MENU_ITEM_ADMIN_OUTCOME_CONFIG: 'Configuração dos resultados',
  MENU_ITEM_ADMIN_PERMISSIONS: 'Politicas e nomes de permissões',
  MENU_ITEM_ADMIN_PLUGINS: 'Ferramentas externas',
  MENU_ITEM_ADMIN_LOCALISATION: 'Seleção de idiomas',
  MENU_EDIT_USER: 'Editar detalhes do usuário',
  MENU_LOGOUT: 'Sair',
  TITLE_HISTORY_CHANGED_BY_APPLICANT: 'Modificado pelo solicitante',
  TITLE_HISTORY_CONSOLIDATION: 'Revisão',
  TITLE_HISTORY_REVIEW: 'Avaliação',
  TITLE_HISTORY_SUBMITTED_BY_APPLICANT: 'Enviado pelo solicitante',
  TITLE_HISTORY_PANEL: 'Histórico da avaliação',
  TITLE_LOGIN_HEADER: 'mFlow - Gerenciador de formulários',
  TITLE_LOGIN: 'Acesso',
  TITLE_APPLICATION_FORM: 'Secções do formulário',
  TITLE_APPLICATION_SUMMARY: 'Availar e enviar',
  TITLE_DETAILS: 'Detalhes',
  TITLE_INTRODUCTION: 'Introdução',
  TITLE_REVIEW_COMMENT: 'Comentário geral',
  TITLE_REVIEW_DECISION: 'Decisão enviada',
  TITLE_REVIEW_SUMMARY: 'Resumo',
  TITLE_STEPS: 'Itens para completar',
  TITLE_OVERVIEW: 'Visão geral',
  STAGE_NOT_FOUND: 'Não encontrado',
  REVIEW_STATUS_IN_PROGRESS: 'Em andamento',
  REVIEW_STATUS_NOT_STARTED: 'Não iniciado',
  REVIEW_STATUS_PENDING_ACTION: 'Avaliação pendente',
  REVIEW_IN_PROGRESS_BY: 'Availação em andamento por',
  REVIEW_CONSOLIDATION_BY: 'Revisado por',
  REVIEW_NOT_FOUND: 'Não encontrado',
  REVIEW_NOT_READY: 'Avaliação bloqueada',
  REVIEW_STARTED: 'Iniciar avaliação',
  REVIEW_SUBMITTED_BY: 'Avaliação enviada por',
  REVIEW_FILTER_EVERYONE: 'a todos',
  REVIEW_FILTER_YOURSELF: 'a mim',
  REVIEW_FILTER_SHOW_TASKS_FOR: 'Mostrar tarefas atribuídas',
  REVIEW_FILTER_STAGE: 'Estágio',
  SUBTITLE_APPLICATION_STEPS: 'Favor completar os passos a seguir antes de enviar o formuário',
  SUBTITLE_APPLICATION_CHANGES_REQUIRED:
    'Alguns problemos foram identificados nas informações enviadas. Favor atualizar e reenviar o formulário',
  SUBTITLE_APPLICATION_SUMMARY: 'Favor avaliar cada secção antes de clicar em enviar',
  SUBTITLE_REVIEW: 'Favor completer as secções que foram atribuídas a si',
  SUBTITLE_SUBMISSION_STEPS: 'Stages for this application:',
  USER_NONREGISTERED: 'nonRegistered',
  VALIDATION_REQUIRED_ERROR: 'Campo obrigatório',
  [Decision.ListOfQuestions]: 'Solitação de informação do solicitante',
  [Decision.ChangesRequested]: 'Solicitação de mudança do avaliador',
  [Decision.Conform]: 'Aprovado',
  [Decision.NonConform]: 'Não aprovado',
  [Decision.NoDecision]: '',
  // To be translated...
  DATE_TODAY: 'Today',
  DATE_YESTERDAY: 'Yesterday',
  DATE_DAYS_AGO: 'days ago',
  DATE_LAST_WEEK: 'Last Week',
  DATE_WEEKS_AGO: 'weeks ago',
  DATE_LAST_MONTH: 'Last Month',
  DATE_MONTHS_AGO: 'months ago',
  DATE_LAST_YEAR: 'Last Year',
  DATE_YEARS_AGO: 'years ago',
  FOOTER_TEXT: 'Powered by mSupply Application Manager',
  FOOTER_COPYRIGHT: '© 2020',
  FILTER_ADD_FILTER: 'Filter',
  FILTER_START_TYPING: 'Start typing...',
  FILTER_REMOVE: 'Remove filter',
  FILTER_NAMED_DATE_TODAY: 'Today',
  FILTER_NAMED_DATE_YESTERDAY: 'Yesterday',
  FILTER_NAMED_DATE_THIS_WEEK: 'This Week',
  FILTER_NAMED_DATE_LAST_WEEK: 'Last Week',
  FILTER_NAMED_DATE_THIS_MONTH: 'This Month',
  FILTER_NAMED_DATE_LAST_MONTH: 'Last Month',
  FILTER_NAMED_DATE_NEXT_MONTH: 'Next Month',
  FILTER_NAMED_DATE_THIS_YEAR: 'This Year',
  FILTER_NAMED_DATE_LAST_YEAR: 'Last Year',
  FILTER_NAMED_DATE_NEXT_YEAR: 'Next Year',
  FILTER_LAST_ACTIVE: 'Last Active',
  FILTER_ASSIGNMENT_STATUS: 'Assignment Status',
  FILTER_ASSIGNMENT_STATUS_TRUE: 'Fully Assigned',
  FILTER_ASSIGNMENT_STATUS_FALSE: 'Not Fully Assigned',
  FILTER_STATUS: 'Status',
  FILTER_OUTCOME: 'Outcome',
  FILTER_STAGE: 'Stage',
  FILTER_ORGANISATION: 'Organisation',
  FILTER_APPLICANT: 'Applicant',
  FILTER_REVIEWER: 'Reviewer',
  FILTER_ASSIGNER: 'Assigner',
  FILTER_REVIEWER_ACTION: 'Reviewer Action',
  FILTER_ASSIGNER_ACTION: 'Assigner Action',
  FILTER_DATE_BEFORE: 'Before',
  FILTER_DATE_AFTER: 'After',
  PAGE_TITLE_HOME: 'Dashboard',
  PAGE_TITLE_LIST: 'Applications List',
  PAGE_TITLE_CREATE: 'New Application',
  PAGE_TITLE_APPLICATION: 'Application %1',
  PAGE_TITLE_REVIEW: 'Review %1',
  PAGE_TITLE_TEMPLATES: 'Templates',
  PAGE_TITLE_LOOKUP_TABLES: 'Lookup Tables',
  PAGE_TITLE_OUTCOMES: 'Outcomes',
  PAGE_TITLE_LOCALISATION: 'Localisations',
  PAGE_TITLE_PLUGINS: 'Plug-ins',
  PAGE_TITLE_PERMISSIONS: 'Permissions',
  DEFAULT_TEMPLATE_CATEGORY_TITLE: 'General',
  DEFAULT_TEMPLATE_CATEGORY_ICON: 'globe',
  TEMPLATE_CATEGORIES: 'Categories',
  TEMPLATE_NO_CATEGORY: 'No category',
  TEMPLATE_NEW_CODE: 'New code',
  TEMPLATE_NEW_TITLE: 'New title',
  TEMPLATE_UI_MENU: 'Application List menu',
  TEMPLATE_UI_DASHBOARD: 'Dashboard',
  TEMPLATE_UI_USER: 'User menu',
  TEMPLATE_UI_ADMIN: 'Admin menu',
  TEMPLATE_ADD_CATEGORY: 'Add Category',
  TEMPLATE_EDIT_CATEGORY: 'Edit Category',
  TEMPLATE_CODE: 'Code',
  TEMPLATE_TITLE: 'Title',
  TEMPLATE_ICON: 'Icon',
  TEMPLATE_BUTTON_SAVE: 'Save',
  TEMPLATE_BUTTON_ADD: 'Add',
  TEMPLATE_APPEARS_IN: 'Appears in',
}
