export default {
  BUTTON_NEXT: 'Next',
  BUTTON_PREVIOUS: 'Previous',
  BUTTON_SUBMIT: 'Submit application',
  BUTTON_REVIEW_APPROVE: 'Approve all ',
  BUTTON_REVIEW_CONTINUE: 'Continue review',
  BUTTON_REVIEW_RESPONSE: 'Review',
  BUTTON_REVIEW_START: 'Start review',
  DATE_APPLICATION_PLACEHOLDER: '31/12/2020',
  TITLE_COMPANY_PLACEHOLDER: 'ABC Company',
  TITLE_REVIEW_SUMMARY: 'Review Summary',
  TITLE_PROGRESS: 'Introduction',
  STAGE_PACEHOLDER: 'assessment',
  SUBTITLE_REVIEW: 'Please complete the sections that have been assigned to you',
}
