export default {
  BUTTON_APPLICATION_START: 'Get started',
  BUTTON_BACK_DASHBOARD: 'Back to dashboard',
  BUTTON_BACK_TO: 'Back to',
  BUTTON_NEXT: 'Next',
  BUTTON_OPTION_YES: 'Yes',
  BUTTON_PREVIOUS: 'Previous',
  BUTTON_REVIEW_APPROVE_ALL: 'Approve all ',
  BUTTON_REVIEW_CONTINUE: 'Continue review',
  BUTTON_REVIEW_RESPONSE: 'Review',
  BUTTON_REVIEW_START: 'Start review',
  BUTTON_SUBMIT: 'Submit application',
  BUTTON_SUMMARY: 'Review & Summary',
  DATE_APPLICATION_PLACEHOLDER: '31/12/2020',
  ERROR_APPLICATION_CREATE: 'Problem to load application creation page',
  ERROR_APPLICATION_ELEMENTS: 'Elements area cannot be displayed',
  ERROR_APPLICATION_OVERVIEW: 'Problem to load application overview',
  ERROR_APPLICATION_PAGE: 'Problem to load application',
  ERROR_APPLICATION_SECTION: 'Section cannot be displayed',
  ERROR_APPLICATION_SUBMISSION: 'Problem to load application submission page',
  ERROR_APPLICATION_SUBMIT: 'Problem to submit application',
  ERROR_APPLICATIONS_LIST: 'Problem to load applications list',
  ERROR_REVIEW_APPLICATION: 'Problem loading application for review',
  ERROR_REVIEW_PAGE: 'Problem to load review',
  ERROR_REVIEW_OVERVIEW: 'Problem to load review homepage',
  ERROR_LOGIN_PASSWORD: 'Oops! Problem with username or password',
  ERROR_SUBMISSION_INVALID: 'Problem to submit application',
  LABEL_ASSIGNED_TO_YOU: 'Assigned to you',
  LABEL_ASSIGNED_TO_OTHER: 'Assigned to another reviewer',
  LABEL_LOGIN_PASSWORD: 'Password',
  LABEL_LOGIN_USERNAME: 'Username',
  LABEL_PROCESSING: 'Processing...',
  LABEL_WELCOME: 'Welcome to IRIMS Application Manager',
  LINK_LOGIN_USER: 'Create new account',
  TITLE_APPLICATION_FORM: 'application form',
  TITLE_APPLICATION_SUBMIT: 'Review & Submit',
  TITLE_COMPANY_PLACEHOLDER: 'ABC Company',
  TITLE_INTRODUCTION: 'Introduction',
  TITLE_REVIEW_SUMMARY: 'Review Summary',
  TITLE_STEPS: 'Steps to complete',
  STAGE_PLACEHOLDER: 'Assessment',
  SUBTITLE_APPLICATION_STEPS:
    'The following sterps will need to be completed before the form can be submitted',
  SUBTITLE_SUBMISSION_STEPS: 'It will be going through the following stages before approval',
  SUBTITLE_REVIEW: 'Please complete the sections that have been assigned to you',
}
