import { Decision } from './generated/graphql'

export default {
  APP_NAME: 'mFlow',
  APP_NAME_SUBHEADER: 'Application Manager',
  ACTION_ASSIGN: 'Assign',
  ACTION_CONTINUE: 'Continue',
  ACTION_START: 'Start',
  ACTION_DATE_RE_SUBMITTED: 'Re-Submitted',
  ACTION_DATE_ASSIGNED: 'Assigned',
  ACTION_DATE_REVIEW_SUBMITTED: 'Review Submitted',
  ACTION_DATE_REVIEW_STARTED: 'Review Started',
  ACTION_MAKE_DECISION: 'Make decision',
  ACTION_RE_REVIEW: 'Re-review',
  ACTION_RE_ASSIGN: 'Re-Assign',
  ACTION_SELF_ASSIGN: 'Self-Assign',
  ACTION_UPDATE: 'Update',
  ACTION_VIEW: 'View',
  ACTION_MAKE_CHANGES: 'Make changes',
  ACTION_EDIT_DRAFT: 'Edit draft',
  OUTCOME_PENDING: 'In progress',
  OUTCOME_APPROVED: 'Approved',
  OUTCOME_REJECTED: 'Rejected',
  OUTCOME_EXPIRED: 'Expired',
  OUTCOME_WITHDRAWN: 'Withdrawn',
  STATUS_SUBMITTED: 'Submitted',
  STATUS_DRAFT: 'Draft',
  STATUS_CHANGES_REQUIRED: 'Changes required',
  STATUS_RE_SUBMITTED: 'Re-submitted',
  STATUS_COMPLETED: 'Completed',
  ASSIGNED: 'assigned',
  ASSIGNED_TO: 'assigned to',
  ASSIGNMENT_NOT_ASSIGNED: 'Not assigned',
  ASSIGNMENT_YOURSELF: 'Yourself',
  ASSIGNMENT_UNASSIGN: 'Un-assign',
  COLUMN_SERIAL: 'Serial',
  COLUMN_LAST_ACTIVE_DATE: 'Last Active',
  COLUMN_DEADLINE_DATE: 'Deadline',
  COLUMN_APPLICATION: 'Application',
  COLUMN_APPLICATION_REVIEW: 'Application',
  COLUMN_APPLICANT: 'Applicant',
  COLUMN_ORGANISATION: 'Organisation',
  COLUMN_CONSOLIDATOR: 'Consolidator',
  COLUMN_STAGE: 'Stage',
  COLUMN_STATUS: 'Status',
  COLUMN_OUTCOME: 'Outcome',
  COLUMN_REVIEWER_ACTION: '',
  COLUMN_APPLICANT_ACTION: '',
  BUTTON_APPLICATION_NEW: 'New application',
  BUTTON_APPLICATION_RESUME: 'Resume',
  BUTTON_APPLICATION_START: 'Get started',
  BUTTON_APPLICATION_SUBMIT: 'Submit application',
  BUTTON_BACK: 'Back',
  BUTTON_BACK_DASHBOARD: 'Back to dashboard',
  BUTTON_CLEAR_SEARCH: 'Clear Search',
  BUTTON_NEXT: 'Next',
  BUTTON_DASHBOARD_NEW: 'New',
  BUTTON_DASHBOARD_VIEW_ALL: 'View All',
  BUTTON_PREVIOUS: 'Previous',
  BUTTON_REVIEW_AGREE_ALL: 'Agree with all',
  BUTTON_REVIEW_APPROVE_ALL: 'Approve all',
  BUTTON_REVIEW_RE_REVIEW: 'Re-Review',
  BUTTON_REVIEW_RESPONSE: 'Review',
  BUTTON_RE_REVIEW_RESPONSE: 'Re-Review',
  BUTTON_REVIEW_SUBMIT: 'Submit review',
  BUTTON_SELF_ASSIGN: 'Self Assign',
  BUTTON_SUMMARY: 'Review & Summary',
  BUTTON_SUBMIT: 'Submit',
  BUTTON_VALIDATING: 'Validating',
  BUTTON_VIEW_APPLICATION: 'View submitted application',
  BUTTON_CANCEL: 'Cancel',
  BUTTON_SUBMIT_APPLICATION: 'Submit application',
  BUTTON_SUMMARY_EDIT: 'Edit',
  BUTTON_ADD_REVIEW: 'Add review',
  BUTTON_VIEW_HISTORY: 'View history',
  PLACEHOLDER_SEARCH: 'Search Applications...',
  DATE_APPLICATION_PLACEHOLDER: '31/12/2020',
  ERROR_APPLICATION_CREATE: 'Problem loading application creation page',
  ERROR_APPLICATION_PAGE: 'Problem loading application',
  ERROR_APPLICATION_SUBMIT: 'Problem submitting application',
  ERROR_APPLICATIONS_LIST: 'Problem loading applications list',
  ERROR_GENERIC: 'Something went wrong',
  ERROR_REVIEW_PAGE: 'Problem loading review',
  ERROR_LOGIN_PASSWORD: 'Oops! Problem with username or password',
  LABEL_APPLICATIONS: 'applications',
  LABEL_APPLICATION_SUBMITTED: 'Application Submitted',
  LABEL_APPLICATION_BACK: 'Back to form',
  LABEL_ASSIGNED_TO_YOU: 'Assigned to you',
  LABEL_ASSIGNED_TO_OTHER: 'Assigned to another reviewer',
  LABEL_ASSIGNMENT_LOCKED: 'Locked for',
  LABEL_ASSIGNMENT_SELF: 'Can be self assigned',
  LABEL_ASSIGNMENT_AVAILABLE: 'Can be self assigned by',
  LABEL_COMMENT: 'Add comment',
  LABEL_CONSOLIDATE: 'Consolidate',
  LABEL_CONSOLIDATION_AGREE: 'Agree',
  LABEL_CONSOLIDATION_DISAGREE: 'Disagree',
  LABEL_CONSOLIDATION_AGREEMENT: 'Agreed',
  LABEL_CONSOLIDATION_DISAGREEMENT: 'Disagreed',
  LABEL_DASHBOARD_NO_APPLICATIONS: "You don't have any applications in progress",
  LABEL_DASHBOARD_START_NEW: 'Start a new %1',
  LABEL_LIST_PER_PAGE: 'Applications per page',
  LABEL_LOADING: 'Loading...',
  LABEL_LOGIN_PASSWORD: 'Password',
  LABEL_LOGIN_USERNAME: 'Username',
  LABEL_LOG_IN: 'Log in',
  LABEL_NO_ORG: 'No organisation',
  LABEL_NO_ORG_SELECT: 'No organisation (act as user only)',
  LABEL_NO_ORG_OPTION: 'Log in without organisation',
  LABEL_PROCESSING: 'Processing...',
  LABEL_PREVIOUS_REVIEW: 'Previous review',
  LABEL_REVIEW: 'Application process',
  LABEL_REVIEW_APPROVE: 'Conform',
  LABEL_REVIEW_DECISION: 'Decision',
  LABEL_REVIEW_APPROVED: 'Approved',
  LABEL_REVIEW_DECLINED: 'Declined',
  LABEL_REVIEW_DECICION_CONFORM: 'Conform',
  LABEL_REVIEW_DECISION_NON_CONFORM: 'Non conform',
  LABEL_REVIEW_IN_PROGRESS: 'Review in Progress',
  LABEL_REVIEW_OVERALL_COMMENT: 'Overall comment',
  LABEL_REVIEW_RESSUBMIT: 'Non conform',
  LABEL_REVIEW_SECTION: 'Please complete the section',
  LABEL_REVIEW_SUBMIT_AS: 'Submit as',
  LABEL_REVIEW_SUBMITTED_AS: 'Submitted as',
  LABEL_REVIEW_REVIEWED_BY: 'Reviewed by',
  LABEL_REVIEW_CONSOLIDATION_BY: 'Consolidation by',
  LABEL_REVIEWER: 'Reviewer',
  LABEL_RESPONSE_UPDATE: 'Update',
  LABEL_RESPONSE_UPDATED: 'Updated',
  LABEL_SECTION_PROBLEM: 'Errors',
  LABEL_SECTION_COMPLETED: 'Completed',
  LABEL_VERIFICATION_FAILED: 'Verificaton Failed',
  LINK_NEW_ACCOUNT: 'Create new account',
  LINK_RESET_PASSWORD: 'Forgot my password',
  MENU_ITEM_DASHBOARD: 'Dashboard',
  MENU_ITEM_APPLICATION_LIST: 'Application List',
  MENU_ITEM_OUTCOMES: 'Outcomes',
  MENU_ITEM_ADMIN_CONFIG: 'Admin Configurations',
  MENU_ITEM_ADMIN_TEMPLATES: 'Templates/Procedures',
  MENU_ITEM_ADMIN_LOOKUP_TABLES: 'Lookup Tables',
  MENU_ITEM_ADMIN_OUTCOME_CONFIG: 'Outcome Configurations',
  MENU_ITEM_ADMIN_PERMISSIONS: 'Permission Policy & Names',
  MENU_ITEM_ADMIN_PLUGINS: 'Plugins',
  MENU_ITEM_ADMIN_LOCALISATION: 'Localisations',
  MENU_EDIT_USER: 'Edit User Details',
  MENU_LOGOUT: 'Log out',
  TITLE_HISTORY_CHANGED_BY_APPLICANT: 'Changed by applicant',
  TITLE_HISTORY_CONSOLIDATION: 'Consolidation',
  TITLE_HISTORY_REVIEW: 'Review',
  TITLE_HISTORY_SUBMITTED_BY_APPLICANT: 'Submitted by applicant',
  TITLE_HISTORY_PANEL: 'Review History',
  TITLE_LOGIN_HEADER: 'mFlow Application Manager',
  TITLE_LOGIN: 'Login',
  TITLE_APPLICATION_FORM: 'application form',
  TITLE_APPLICATION_SUMMARY: 'Review and Submit',
  TITLE_DETAILS: 'Details',
  TITLE_INTRODUCTION: 'Introduction',
  TITLE_REVIEW_COMMENT: 'Overall comment',
  TITLE_REVIEW_DECISION: 'Submitted decision',
  TITLE_REVIEW_SUMMARY: 'Review Summary',
  TITLE_STEPS: 'Steps to complete',
  TITLE_OVERVIEW: 'Overview',
  STAGE_NOT_FOUND: 'Not Found',
  REVIEW_STATUS_IN_PROGRESS: 'In progress',
  REVIEW_STATUS_NOT_STARTED: 'Not started',
  REVIEW_STATUS_PENDING_ACTION: 'Pending reviewer action',
  REVIEW_IN_PROGRESS_BY: 'Review in progress by',
  REVIEW_CONSOLIDATION_BY: 'Consolidation by',
  REVIEW_NOT_FOUND: 'Not found',
  REVIEW_NOT_READY: 'Not ready to review',
  REVIEW_STARTED: 'Review started',
  REVIEW_SUBMITTED_BY: 'Review submitted by',
  REVIEW_FILTER_EVERYONE: 'Everyone',
  REVIEW_FILTER_YOURSELF: 'Yourself',
  REVIEW_FILTER_SHOW_TASKS_FOR: 'Show tasks for',
  REVIEW_FILTER_STAGE: 'Stage',
  SUBTITLE_APPLICATION_STEPS:
    'The following steps will need to be completed before the form can be submitted',
  SUBTITLE_APPLICATION_CHANGES_REQUIRED:
    'There are issues with some of the information you supplied. Please update and resubmit the form.',
  SUBTITLE_APPLICATION_SUMMARY: 'Please review each section before submitting form',
  SUBTITLE_REVIEW: 'Please complete the sections that have been assigned to you',
  SUBTITLE_SUBMISSION_STEPS: 'Stages for this application:',
  USER_NONREGISTERED: 'nonRegistered',
  VALIDATION_REQUIRED_ERROR: 'Field is required',
  [Decision.ListOfQuestions]: 'List Of Questions',
  [Decision.ChangesRequested]: 'Changes Requested',
  [Decision.Conform]: 'Conform',
  [Decision.NonConform]: 'Non Conform',
  [Decision.NoDecision]: '',
  DATE_TODAY: 'Today',
  DATE_YESTERDAY: 'Yesterday',
  DATE_DAYS_AGO: 'days ago',
  DATE_LAST_WEEK: 'Last Week',
  DATE_WEEKS_AGO: 'weeks ago',
  DATE_LAST_MONTH: 'Last Month',
  DATE_MONTHS_AGO: 'months ago',
  DATE_LAST_YEAR: 'Last Year',
  DATE_YEARS_AGO: 'years ago',
  FOOTER_TEXT: 'Powered by mSupply Application Manager',
  FOOTER_COPYRIGHT: '© 2020',
  FILTER_ADD_FILTER: 'Filter',
  FILTER_START_TYPING: 'Start typing...',
  FILTER_REMOVE: 'Remove filter',
  FILTER_NAMED_DATE_TODAY: 'Today',
  FILTER_NAMED_DATE_YESTERDAY: 'Yesterday',
  FILTER_NAMED_DATE_THIS_WEEK: 'This Week',
  FILTER_NAMED_DATE_LAST_WEEK: 'Last Week',
  FILTER_NAMED_DATE_THIS_MONTH: 'This Month',
  FILTER_NAMED_DATE_LAST_MONTH: 'Last Month',
  FILTER_NAMED_DATE_NEXT_MONTH: 'Next Month',
  FILTER_NAMED_DATE_THIS_YEAR: 'This Year',
  FILTER_NAMED_DATE_LAST_YEAR: 'Last Year',
  FILTER_NAMED_DATE_NEXT_YEAR: 'Next Year',
  FILTER_LAST_ACTIVE: 'Last Active',
  FILTER_ASSIGNMENT_STATUS: 'Assignment Status',
  FILTER_ASSIGNMENT_STATUS_TRUE: 'Fully Assigned',
  FILTER_ASSIGNMENT_STATUS_FALSE: 'Not Fully Assigned',
  FILTER_STATUS: 'Status',
  FILTER_OUTCOME: 'Outcome',
  FILTER_STAGE: 'Stage',
  FILTER_ORGANISATION: 'Organisation',
  FILTER_APPLICANT: 'Applicant',
  FILTER_REVIEWER: 'Reviewer',
  FILTER_ASSIGNER: 'Assigner',
  FILTER_REVIEWER_ACTION: 'Reviewer Action',
  FILTER_ASSIGNER_ACTION: 'Assigner Action',
  FILTER_DATE_BEFORE: 'Before',
  FILTER_DATE_AFTER: 'After',
  PAGE_TITLE_HOME: 'Dashboard',
  PAGE_TITLE_LIST: 'Applications List',
  PAGE_TITLE_CREATE: 'New Application',
  PAGE_TITLE_APPLICATION: 'Application %1',
  PAGE_TITLE_REVIEW: 'Review %1',
  PAGE_TITLE_TEMPLATES: 'Templates',
  PAGE_TITLE_LOOKUP_TABLES: 'Lookup Tables',
  PAGE_TITLE_OUTCOMES: 'Outcomes',
  PAGE_TITLE_LOCALISATION: 'Localisations',
  PAGE_TITLE_PLUGINS: 'Plug-ins',
  PAGE_TITLE_PERMISSIONS: 'Permissions',
  DEFAULT_TEMPLATE_CATEGORY_TITLE: 'General',
  DEFAULT_TEMPLATE_CATEGORY_ICON: 'globe',
  TEMPLATE_CATEGORIES: 'Categories',
  TEMPLATE_NO_CATEGORY: 'No category',
  TEMPLATE_NEW_CODE: 'New code',
  TEMPLATE_NEW_TITLE: 'New title',
  TEMPLATE_UI_MENU: 'Application List menu',
  TEMPLATE_UI_DASHBOARD: 'Dashboard',
  TEMPLATE_UI_USER: 'User menu',
  TEMPLATE_UI_ADMIN: 'Admin menu',
  TEMPLATE_ADD_CATEGORY: 'Add Category',
  TEMPLATE_EDIT_CATEGORY: 'Edit Category',
  TEMPLATE_CODE: 'Code',
  TEMPLATE_TITLE: 'Title',
  TEMPLATE_ICON: 'Icon',
  TEMPLATE_BUTTON_SAVE: 'Save',
  TEMPLATE_BUTTON_ADD: 'Add',
  TEMPLATE_APPEARS_IN: 'Appears in',
  OUTCOMES_TABLE_PAGINATION_TEXT: 'Items per page',
  APP_LINK_LINKED_APPLICATIONS: 'Linked Application',
  APP_LINK_NAME: 'Name',
  APP_LINK_SERIAL: 'Serial',
  APP_LINK_TYPE: 'Application Type',
  APP_LINK_COMPLETED: 'Date Completed',
}
