export default {
  APP_NAME: 'conforma',
  APP_NAME_SUBHEADER: 'Application Manager',
  OK: 'OK',
  CANCEL: 'Cancel',
  YES: 'Yes',
  NO: 'No',
  APPLICATIONS_LIST_EMPTY: 'No applications found',
  APPLICATION_MISSING_TEMPLATE: '',
  APPLICATION_OTHER_CHANGES_MADE: 'This is a new submission and will require a review.',
  TRIGGER_RUNNING: 'Trigger is running. Please wait to reload page again.',
  LOGIN_WELCOME: 'Welcome, %1',
  LOGIN_ORG_SELECT: 'Please select an organisation',
  LOGIN_REDIRECT_TO_REGISTRATION: 'Re-directing to user registration application...',
  ACTION_ASSIGN: 'Assign',
  ACTION_CONTINUE: 'Continue',
  ACTION_START: 'Start',
  ACTION_DATE_RE_SUBMITTED: 'Re-Submitted',
  ACTION_DATE_ASSIGNED: 'Assigned',
  ACTION_DATE_REVIEW_SUBMITTED: 'Review Submitted',
  ACTION_DATE_REVIEW_STARTED: 'Review Started',
  ACTION_MAKE_DECISION: 'Make decision',
  ACTION_RE_REVIEW: 'Re-review',
  ACTION_RE_ASSIGN: 'Re-Assign',
  ACTION_SELF_ASSIGN: 'Self-Assign',
  ACTION_UPDATE: 'Update',
  ACTION_VIEW: 'View',
  ACTION_MAKE_CHANGES: 'Make changes',
  ACTION_EDIT_DRAFT: 'Edit draft',
  APPLICATION_DELETION_CONFIRM_TITLE: 'Delete application',
  APPLICATION_DELETION_CONFIRM_MESSAGE:
    'Please confirm you would like to delete a draft application',
  OUTCOME_PENDING: 'In progress',
  OUTCOME_APPROVED: 'Approved',
  OUTCOME_REJECTED: 'Rejected',
  OUTCOME_EXPIRED: 'Expired',
  OUTCOME_WITHDRAWN: 'Withdrawn',
  STATUS_SUBMITTED: 'Submitted',
  STATUS_DRAFT: 'Draft',
  STATUS_CHANGES_REQUIRED: 'Changes required',
  STATUS_RE_SUBMITTED: 'Re-submitted',
  STATUS_COMPLETED: 'Completed',
  ASSIGNED: 'assigned',
  ASSIGNED_TO: 'assigned to',
  ASSIGNMENT_NOT_ASSIGNED: 'Not assigned',
  ASSIGNMENT_YOURSELF: 'Yourself',
  ASSIGNMENT_UNASSIGN: 'Un-assign',
  ASSIGNMENT_REASSIGN: 'Re-assign',
  COLUMN_SERIAL: 'Serial',
  COLUMN_LAST_ACTIVE_DATE: 'Last Active',
  COLUMN_DEADLINE_DATE: 'Deadline',
  COLUMN_APPLICATION: 'Application',
  COLUMN_APPLICATION_REVIEW: 'Application',
  COLUMN_APPLICANT: 'Applicant',
  COLUMN_ORGANISATION: 'Organisation',
  COLUMN_CONSOLIDATOR: 'Consolidator',
  COLUMN_STAGE: 'Stage',
  COLUMN_STATUS: 'Status',
  COLUMN_OUTCOME: 'Outcome',
  COLUMN_REVIEWER_ACTION: '',
  COLUMN_APPLICANT_ACTION: '',
  BUTTON_APPLICATION_NEW: 'New application',
  BUTTON_APPLICATION_RESUME: 'Resume',
  BUTTON_APPLICATION_START: 'Get started',
  BUTTON_APPLICATION_SUBMIT: 'Submit application',
  BUTTON_BACK: 'Back',
  BUTTON_BACK_DASHBOARD: 'Back to dashboard',
  BUTTON_CLOSE: 'Close',
  BUTTON_CLEAR_SEARCH: 'Clear Search',
  BUTTON_NEXT: 'Next',
  BUTTON_DASHBOARD_NEW: 'New',
  BUTTON_DASHBOARD_VIEW_ALL: 'View All',
  BUTTON_PREVIOUS: 'Previous',
  BUTTON_REVIEW_AGREE_ALL: 'Agree with all',
  BUTTON_REVIEW_APPROVE_ALL: 'Approve all',
  BUTTON_REVIEW_RE_REVIEW: 'Re-Review',
  BUTTON_REVIEW_RESPONSE: 'Review',
  BUTTON_RE_REVIEW_RESPONSE: 'Re-Review',
  BUTTON_REVIEW_SUBMIT: 'Submit review',
  BUTTON_SELF_ASSIGN: 'Self Assign',
  BUTTON_SUMMARY: 'Review & Summary',
  BUTTON_SUBMIT: 'Submit',
  BUTTON_VALIDATING: 'Validating',
  BUTTON_VIEW_APPLICATION: 'View submitted application',
  BUTTON_CANCEL: 'Cancel',
  BUTTON_SUBMIT_APPLICATION: 'Submit application',
  BUTTON_SUMMARY_EDIT: 'Edit',
  BUTTON_ADD_REVIEW: 'Add review',
  BUTTON_VIEW_HISTORY: 'View history',
  PLACEHOLDER_SEARCH: 'Search Applications...',
  DATE_APPLICATION_PLACEHOLDER: '31/12/2020',
  ERROR_APPLICATION_CREATE: 'Problem loading application creation page',
  ERROR_APPLICATION_DELETE: 'Problem deleting application',
  ERROR_APPLICATION_PAGE: 'Problem loading application',
  ERROR_APPLICATION_SUBMIT: 'Problem submitting application',
  ERROR_APPLICATIONS_LIST: 'Problem loading applications list',
  ERROR_FOUND: 'Errors found',
  ERROR_GENERIC: 'Something went wrong',
  ERROR_REVIEW_PAGE: 'Problem loading review',
  ERROR_LOGIN_PASSWORD: 'Oops! Problem with username or password',
  LABEL_APPLICATIONS: 'applications',
  LABEL_APPLICATION_SUBMITTED: 'Application Submitted',
  LABEL_APPLICATION_BACK: 'Back to form',
  LABEL_ASSIGNED_TO_YOU: 'Assigned to you',
  LABEL_ASSIGNED_TO_OTHER: 'Assigned to another reviewer',
  LABEL_ASSIGNMENT_LOCKED: 'Locked for',
  LABEL_ASSIGNMENT_SELF: 'Can be self assigned',
  LABEL_ASSIGNMENT_AVAILABLE: 'Can be self assigned by',
  LABEL_COMMENT: 'Add comment',
  LABEL_CONSOLIDATE: 'Consolidate',
  LABEL_CONSOLIDATION_AGREE: 'Agree',
  LABEL_CONSOLIDATION_DISAGREE: 'Disagree',
  LABEL_CONSOLIDATION_AGREEMENT: 'Agreed',
  LABEL_CONSOLIDATION_DISAGREEMENT: 'Disagreed',
  LABEL_DASHBOARD_NO_APPLICATIONS: "You don't have any applications in progress",
  LABEL_DASHBOARD_START_NEW: 'Start a new %1',
  LABEL_EXPORT: 'Export',
  LABEL_IMPORT: 'Import',
  LABEL_LIST_PER_PAGE: 'Applications per page',
  LABEL_LOADING: 'Loading...',
  LABEL_LOGIN_PASSWORD: 'Password',
  LABEL_LOGIN_USERNAME: 'Username',
  LABEL_LOG_IN: 'Log in',
  LABEL_FILE_IMPORT_CSV: 'Import CSV',
  LABEL_FILE_UPLOAD_TITLE: 'File input & upload',
  LABEL_FILE_UPLOAD: 'Choose a File',
  LABEL_FILE_UPLOAD_CHOSEN: 'File Chosen: ',
  LABEL_FILE_UPLOAD_PLACEHOLDER: 'Use the above bar to browse your file system',
  LABEL_FILE_DOWNLOAD_ERROR: 'Error trying to download',
  LABEL_NO_ORG: 'No organisation',
  LABEL_NO_ORG_SELECT: 'No organisation (act as user only)',
  LABEL_NO_ORG_OPTION: 'Log in without organisation',
  LABEL_PROCESSING: 'Processing...',
  LABEL_PREVIOUS_REVIEW: 'Previous review',
  LABEL_REVIEW: 'Application process',
  LABEL_REVIEW_APPROVE: 'Conform',
  LABEL_REVIEW_DECISION: 'Decision',
  LABEL_REVIEW_APPROVED: 'Approved',
  LABEL_REVIEW_DECLINED: 'Declined',
  LABEL_REVIEW_DECICION_CONFORM: 'Conform',
  LABEL_REVIEW_DECISION_NON_CONFORM: 'Non conform',
  LABEL_REVIEW_IN_PROGRESS: 'Review in Progress',
  LABEL_REVIEW_MAKE_DECISION_BY: 'Awaiting decision making by',
  LABEL_REVIEW_OVERALL_COMMENT: 'Overall comment',
  LABEL_REVIEW_RESSUBMIT: 'Non conform',
  LABEL_REVIEW_SECTION: 'Please complete the section',
  LABEL_REVIEW_SUBMIT_AS: 'Submit as',
  LABEL_REVIEW_SUBMITTED_AS: 'Submitted as',
  LABEL_REVIEWER: 'Reviewer',
  LABEL_REASSIGN_TO: 'Reassign to',
  LABEL_UNASSIGN_FROM: 'Unassign from',
  LABEL_RESPONSE_UPDATE: 'Update',
  LABEL_RESPONSE_UPDATED: 'Updated',
  LABEL_SECTION_PROBLEM: 'Errors',
  LABEL_SECTION_COMPLETED: 'Completed',
  LABEL_SUBMITTING: 'Submitting...',
  LABEL_TRY_AGAIN: 'Try again',
  LABEL_VERIFICATION_FAILED: 'Verificaton Failed',
  REVIEW_SUBMISSION_CONFIRM_TITLE: 'Submitting Review',
  REVIEW_SUBMISSION_CONFIRM_MESSAGE: 'Are you sure?',
  REVIEW_SUBMISSION_CONFIRM_OPTION: 'Submitting Review',
  REVIEW_SUBMISSION_FAIL: 'Not all sections have been reviewed',
  REVIEW_SUBMISSION_ERROR: 'Something wrong with server - review mutation failed',
  REVIEW_DECISION_SET_FAIL_TITLE: 'Problem submitting review',
  REVIEW_DECISION_SET_FAIL_MESSAGE: 'Please select a decision: List Of Questions or Non Conformity',
  REVIEW_DECISION_MISMATCH_TITLE: 'Final decision',
  REVIEW_DECISION_MISMATCH_MESSAGE:
    'You have made a different decision than the previous reviewer.\nAre you sure you wish to proceed with your decision?',
  REVIEW_STATUS_PENDING_TITLE: 'Please reload review before submitting',
  REVIEW_STATUS_PENDING_MESSAGE:
    'All your existing decisions will be kept.\nYou will be redirected to the home page now. Click "Start" in there to reload page with latest responses to review.',
  LINK_NEW_ACCOUNT: 'Create new account',
  LINK_RESET_PASSWORD: 'Forgot my password',
  MENU_ITEM_DASHBOARD: 'Dashboard',
  MENU_ITEM_APPLICATION_LIST: 'Application List',
  MENU_ITEM_OUTCOMES: 'Outcomes',
  MENU_ITEM_ADMIN_CONFIG: 'Admin Configurations',
  MENU_ITEM_ADMIN_TEMPLATES: 'Templates/Procedures',
  MENU_ITEM_ADMIN_LOOKUP_TABLES: 'Lookup Tables',
  MENU_ITEM_ADMIN_OUTCOME_CONFIG: 'Outcome Configurations',
  MENU_ITEM_ADMIN_PERMISSIONS: 'Permission Policy & Names',
  MENU_ITEM_ADMIN_PLUGINS: 'Plugins',
  MENU_ITEM_ADMIN_LOCALISATION: 'Localisations',
  MENU_EDIT_USER: 'Edit User Details',
  MENU_CHANGE_LANGUAGE: 'Change Language',
  MENU_LOGOUT: 'Log out',
  MENU_LANGUAGE_SELECT: 'Please select a language',
  MENU_LANGUAGE_CURRENT: 'current',
  TITLE_HISTORY_CHANGED_BY_APPLICANT: 'Changed by applicant',
  TITLE_HISTORY_CONSOLIDATION: 'Consolidation',
  TITLE_HISTORY_REVIEW: 'Review',
  TITLE_HISTORY_SUBMITTED_BY_APPLICANT: 'Submitted by applicant',
  TITLE_HISTORY_PANEL: 'Review History',
  TITLE_LOGIN_HEADER: 'Application Manager',
  TITLE_LOGIN: 'Login',
  TITLE_APPLICATION_FORM: 'application form',
  TITLE_APPLICATION_SUMMARY: 'Review and Submit',
  TITLE_APPLICATION_COMPLETED: 'Completed application',
  TITLE_DETAILS: 'Details',
  TITLE_INTRODUCTION: 'Introduction',
  TITLE_REVIEW_COMMENT: 'Overall comment',
  TITLE_REVIEW_DECISION: 'Submitted decision',
  TITLE_REVIEW_SUMMARY: 'Review Summary',
  TITLE_STEPS: 'Steps to complete',
  TITLE_OVERVIEW: 'Overview',
  STAGE_NOT_FOUND: 'Not Found',
  REVIEW_STATUS_IN_PROGRESS: 'In progress',
  REVIEW_STATUS_NOT_STARTED: 'Not started',
  REVIEW_STATUS_PENDING_ACTION: 'Pending reviewer action',
  REVIEW_IN_PROGRESS_BY: 'Review in progress by',
  REVIEW_DONE_BY: 'Review submitted by',
  CONSOLIDATION_IN_PROGRESS_BY: 'Consolidation by',
  CONSOLIDATION_DONE_BY: 'Consolidation submitted by',
  REVIEW_NOT_FOUND: 'Not found',
  REVIEW_NOT_READY: 'Not ready to review',
  REVIEW_STARTED: 'Review started',
  REVIEW_SUBMITTED_BY: 'Review submitted by',
  REVIEW_FILTER_EVERYONE: 'Everyone',
  REVIEW_FILTER_YOURSELF: 'Yourself',
  REVIEW_FILTER_SHOW_TASKS_FOR: 'Show tasks for',
  REVIEW_FILTER_STAGE: 'Stage',
  REVIEW_TAB_OVERVIEW: 'Overview',
  REVIEW_TAB_ASSIGNMENT: 'Assignment',
  REVIEW_TAB_SUMMARY: 'Summary',
  REVIEW_TAB_NOTES: 'Internal Notes',
  REVIEW_TAB_DOCUMENTS: 'Documents',
  SUBTITLE_APPLICATION_STEPS:
    'The following steps will need to be completed before the form can be submitted',
  SUBTITLE_APPLICATION_CHANGES_REQUIRED:
    'There are issues with some of the information you supplied. Please update and resubmit the form.',
  SUBTITLE_APPLICATION_SUMMARY: 'Please review each section before submitting form',
  SUBTITLE_REVIEW: 'Please complete the sections that have been assigned to you',
  SUBTITLE_SUBMISSION_STEPS: 'Stages for this application:',
  VALIDATION_REQUIRED_ERROR: 'Field is required',
  DECISION_LIST_OF_QUESTIONS: 'List Of Questions',
  DECISION_CHANGES_REQUESTED: 'Changes Requested',
  DECISION_CONFORM: 'Conform',
  DECISION_NON_CONFORM: 'Non-conform',
  DECISION_NO_DECISION: '',
  DATE_TODAY: 'Today',
  DATE_YESTERDAY: 'Yesterday',
  DATE_DAYS_AGO: 'days ago',
  DATE_LAST_WEEK: 'Last Week',
  DATE_WEEKS_AGO: 'weeks ago',
  DATE_LAST_MONTH: 'Last Month',
  DATE_MONTHS_AGO: 'months ago',
  DATE_LAST_YEAR: 'Last Year',
  DATE_YEARS_AGO: 'years ago',
  FOOTER_TEXT: 'Powered by mSupply Application Manager',
  FILTER_ADD_FILTER: 'Filter',
  FILTER_START_TYPING: 'Start typing...',
  FILTER_REMOVE: 'Remove filter',
  FILTER_NAMED_DATE_TODAY: 'Today',
  FILTER_NAMED_DATE_YESTERDAY: 'Yesterday',
  FILTER_NAMED_DATE_THIS_WEEK: 'This Week',
  FILTER_NAMED_DATE_LAST_WEEK: 'Last Week',
  FILTER_NAMED_DATE_THIS_MONTH: 'This Month',
  FILTER_NAMED_DATE_LAST_MONTH: 'Last Month',
  FILTER_NAMED_DATE_NEXT_MONTH: 'Next Month',
  FILTER_NAMED_DATE_THIS_YEAR: 'This Year',
  FILTER_NAMED_DATE_LAST_YEAR: 'Last Year',
  FILTER_NAMED_DATE_NEXT_YEAR: 'Next Year',
  FILTER_LAST_ACTIVE: 'Last Active',
  FILTER_ASSIGNMENT_STATUS: 'Assignment Status',
  FILTER_ASSIGNMENT_STATUS_TRUE: 'Fully Assigned',
  FILTER_ASSIGNMENT_STATUS_FALSE: 'Not Fully Assigned',
  FILTER_STATUS: 'Status',
  FILTER_OUTCOME: 'Outcome',
  FILTER_STAGE: 'Stage',
  FILTER_ORGANISATION: 'Organisation',
  FILTER_APPLICANT: 'Applicant',
  FILTER_REVIEWER: 'Reviewer',
  FILTER_ASSIGNER: 'Assigner',
  FILTER_REVIEWER_ACTION: 'Reviewer Action',
  FILTER_ASSIGNER_ACTION: 'Assigner Action',
  FILTER_DATE_BEFORE: 'Before',
  FILTER_DATE_AFTER: 'After',
  PAGE_TITLE_HOME: 'Dashboard',
  PAGE_TITLE_LIST: 'Applications List',
  PAGE_TITLE_CREATE: 'New Application',
  PAGE_TITLE_APPLICATION: 'Application %1',
  PAGE_TITLE_REVIEW: 'Review %1',
  PAGE_TITLE_TEMPLATES: 'Templates',
  PAGE_TITLE_LOOKUP_TABLES: 'Lookup Tables',
  PAGE_TITLE_OUTCOMES: 'Outcomes',
  PAGE_TITLE_LOCALISATION: 'Localisations',
  PAGE_TITLE_PLUGINS: 'Plug-ins',
  PAGE_TITLE_PERMISSIONS: 'Permissions',
  DEFAULT_TEMPLATE_CATEGORY_TITLE: 'General',
  DEFAULT_TEMPLATE_CATEGORY_ICON: 'globe',
  TEMPLATE_GEN_BUTTON_AVAILABLE: 'Make Available',
  TEMPLATE_GEN_BUTTON_AVAILABLE_DISABLED:
    'At least one template with the same code is already available, or this template already available',
  TEMPLATE_GEN_BUTTON_DRAFT: 'Make Draft',
  TEMPLATE_GEN_BUTTON_DRAFT_DISABLED: 'Already has appications or is draft',
  TEMPLATE_GEN_BUTTON_DISABLE: 'Disable',
  TEMPLATE_GEN_BUTTON_DISABLE_DISABLED: 'Already disabled',
  TEMPLATE_CATEGORIES: 'Categories',
  TEMPLATE_NO_CATEGORY: 'No category',
  TEMPLATE_NEW_CODE: 'New code',
  TEMPLATE_NEW_TITLE: 'New title',
  TEMPLATE_UI_MENU: 'Application List menu',
  TEMPLATE_UI_DASHBOARD: 'Dashboard',
  TEMPLATE_UI_USER: 'User menu',
  TEMPLATE_UI_ADMIN: 'Admin menu',
  TEMPLATE_ADD_CATEGORY: 'Add Category',
  TEMPLATE_EDIT_CATEGORY: 'Edit Category',
  TEMPLATE_CODE: 'Code',
  TEMPLATE_TITLE: 'Title',
  TEMPLATE_ICON: 'Icon',
  TEMPLATE_LABEL_ACTION: 'Action',
  TEMPLATE_LABEL_ACTION_DESCRIPTION: 'new action description',
  TEMPLATE_LABEL_ACTION_MESSAGE: 'new action message',
  TEMPLATE_LABEL_ACTION_ON_TOP: 'Add on top',
  TEMPLATE_LABEL_DESCRIPTION: 'Description',
  TEMPLATE_LABEL_CONDITION: 'Condition',
  TEMPLATE_LABEL_SEQUENTIAL: 'Is Sequential',
  TEMPLATE_BUTTON_ACTION_ADD: 'Add Action',
  TEMPLATE_BUTTON_SAVE: 'Save',
  TEMPLATE_BUTTON_ADD: 'Add',
  TEMPLATE_BUTTON_CONFIRM: 'Confirm',
  TEMPLATE_BUTTON_CLOSE: 'Close',
  TEMPLATE_BUTTON_REMOVE: 'Remove',
  TEMPLATE_APPEARS_IN: 'Appears in',
  TEMPLATE_MESSAGE_SAVE_AND_CLOSE: 'There are changes not saved. Would you like to save and close?',
  TEMPLATE_MESSAGE_SAVE_SUCCESS: 'Changes saved',
  TEMPLATE_MESSAGE_SAVE_DISABLED: 'No changes',
  TEMPLATE_MESSAGE_REMOVE_ELEMENT_TITLE: 'Remove element',
  TEMPLATE_MESSAGE_REMOVE_ELEMENT_CONTENT: 'Are you sure you would like to remove this element?',
  UNASSIGN_TITLE: 'Unassignment of reviewer',
  UNASSIGN_MESSAGE: 'Are you sure you would like to un-assign?',
  OUTCOMES_TABLE_PAGINATION_TEXT: 'Items per page',
  APP_LINK_LINKED_APPLICATIONS: 'Linked Applications',
  APP_LINK_NAME: 'Name',
  APP_LINK_SERIAL: 'Serial',
  APP_LINK_TYPE: 'Application Type',
  APP_LINK_COMPLETED: 'Date Completed',
  LOOKUP_ERROR_NOT_FOUND: 'No lookup-table found!',
  LOOKUP_ERROR_TITLE: 'Error loading lookup-table',
  LOOKUP_TABLE_HEADER_LABEL: 'Label',
  LOOKUP_TABLE_HEADER_NAME: 'Table Name',
  LOOKUP_TABLE_HEADER_ACTIONS: 'Actions',
  LOOKUP_TABLE_VIEW: 'View lookup table',
  LOOKUP_TABLE_IMPORT: 'Import lookup table',
  LOOKUP_TABLE_IMPORT_INTO: 'Import into Lookup-table:',
  LOOKUP_TABLE_IMPORT_OTHER: 'Import another CSV',
  LOOKUP_TABLE_DOWNLOAD: "Download '%1' table",
  LOOKUP_TABLE_FIELD_NAME: 'Database Field-name',
  LOOKUP_TABLE_LABEL: 'Lookup-table Label',
  LOOKUP_TABLE_NAME: 'Table name',
  LOOKUP_TABLE_ADD: 'Add new Lookup-table',
  LOOKUP_TABLE_TITLE: 'Lookup table:',
  LOOKUP_TABLE_CONTENTS: 'View individual lookup-table and its contents',
  LOOKUP_TABLE_SUBTITLE: 'This page contains the list of all lookup-tables',
  LOOKUP_TABLE_SUCCESS_CREATED: 'Lookup table %1 has been successfully created.',
  LOOKUP_TABLE_SUCCESS_UPDATED: 'Lookup table %1 has been successfully updated.',
  LOOKUP_TABLES_TITLE: 'Lookup Tables',
  NO_MATCH_404_DEFAULT_HEADER: 'Something went wrong',
  NO_MATCH_404_DEFAULT_CONTENT: 'Page not found',
  NO_MATCH_404_GO_BACK: 'Go back',
  TIMELINE_APPLICATION_STARTED: 'Application started',
  TIMELINE_ASSIGNED: 'Reviewer %1 was assigned Sections %2 by %3',
}
