export default {
  _APP_NAME: 'conforma',
  _APP_NAME_SUBHEADER: 'Application Manager',
  ACTION_ASSIGN: 'Assign',
  ACTION_CONTINUE: 'Continue',
  ACTION_START: 'Start',
  ACTION_DATE_RE_SUBMITTED: 'Re-Submitted',
  ACTION_DATE_ASSIGNED: 'Assigned',
  ACTION_DATE_REVIEW_SUBMITTED: 'Review Submitted',
  ACTION_DATE_REVIEW_STARTED: 'Review Started',
  ACTION_LOCKED: 'Locked',
  ACTION_MAKE_DECISION: 'Make decision',
  ACTION_PENDING: 'Re-consolidate',
  ACTION_RE_REVIEW: 'Re-review',
  ACTION_RE_ASSIGN: 'Re-Assign',
  ACTION_SELF_ASSIGN: 'Self-Assign',
  ACTION_UNASSIGN: 'Un-assign',
  ACTION_UPDATE: 'Update',
  ACTION_VIEW: 'View',
  ACTION_MAKE_CHANGES: 'Make changes',
  ACTION_EDIT_DRAFT: 'Edit draft',
  APP_LINK_LINKED_APPLICATIONS: 'Linked Applications',
  APP_LINK_NAME: 'Name',
  APP_LINK_SERIAL: 'Serial',
  APP_LINK_TYPE: 'Application Type',
  APP_LINK_COMPLETED: 'Date Completed',
  APPLICATION_DELETION_CONFIRM_TITLE: 'Delete application',
  APPLICATION_DELETION_CONFIRM_MESSAGE:
    'Please confirm you would like to delete a draft application',
  APPLICATIONS_LIST_EMPTY: 'No applications found',
  APPLICATION_MISSING_TEMPLATE: "The applicantion's template was not found",
  APPLICATION_OTHER_CHANGES_MADE: 'This is a new submission and will require a review.',
  ASSIGNED: 'assigned',
  ASSIGNED_TO: 'assigned to',
  ASSIGNMENT_NOT_ASSIGNED: 'Not assigned',
  ASSIGNMENT_YOURSELF: 'Yourself',
  ASSIGNMENT_ERROR_TITLE: 'Assignment update error',
  ASSIGNMENT_ERROR_GENERAL: 'Could not complete assignment',
  ASSIGNMENT_ERROR_UNASSIGN: 'Could not unassign reviewer(s)',
  BUTTON_APPLICATION_NEW: 'New application',
  BUTTON_APPLICATION_RESUME: 'Resume',
  BUTTON_APPLICATION_START: 'Get started',
  BUTTON_APPLICATION_SUBMIT: 'Submit application',
  BUTTON_BACK: 'Back',
  BUTTON_BACK_DASHBOARD: 'Back to dashboard',
  BUTTON_CLOSE: 'Close',
  BUTTON_SAVE: 'Save',
  BUTTON_CONFIRM: 'Confirm',
  BUTTON_REMOVE: 'Remove',
  BUTTON_CLEAR_SEARCH: 'Clear Search',
  BUTTON_NEXT: 'Next',
  BUTTON_DASHBOARD_NEW: 'New',
  BUTTON_DASHBOARD_VIEW_ALL: 'View All',
  BUTTON_PREVIOUS: 'Previous',
  BUTTON_REVIEW_AGREE_ALL: 'Agree with all',
  BUTTON_REVIEW_APPROVE_ALL: 'Approve all',
  BUTTON_REVIEW_RE_REVIEW: 'Re-Review',
  BUTTON_REVIEW_RESPONSE: 'Review',
  BUTTON_RE_REVIEW_RESPONSE: 'Re-Review',
  BUTTON_PREVIEW_DECISION: 'Preview Decision',
  BUTTON_REVIEW_SUBMIT: 'Submit review',
  BUTTON_SELF_ASSIGN: 'Self Assign',
  BUTTON_SUMMARY: 'Review & Summary',
  BUTTON_SUBMIT: 'Submit',
  BUTTON_VALIDATING: 'Validating',
  BUTTON_VIEW_APPLICATION: 'View submitted application',
  BUTTON_SUBMIT_APPLICATION: 'Submit application',
  BUTTON_SUMMARY_EDIT: 'Edit',
  BUTTON_ADD_REVIEW: 'Add review',
  BUTTON_VIEW_HISTORY: 'View history',
  MODAL_CONFIRM_TITLE: 'Are you sure?',
  COLUMN_SERIAL: 'Serial',
  COLUMN_LAST_ACTIVE_DATE: 'Last Active',
  COLUMN_LAST_ACTIVE_DATE_TOOLTIP: 'Date applicant last submitted changes',
  COLUMN_DEADLINE_DATE: 'Deadline',
  COLUMN_DEADLINE_DATE_TOOLTIP: 'Deadline for applicant to respond',
  COLUMN_APPLICATION: 'Application',
  COLUMN_APPLICATION_REVIEW: 'Application',
  COLUMN_APPLICANT: 'Applicant',
  COLUMN_ORGANISATION: 'Organisation',
  COLUMN_CONSOLIDATOR: 'Consolidator',
  COLUMN_STAGE: 'Stage',
  COLUMN_STATUS: 'Status',
  COLUMN_OUTCOME: 'Outcome',
  COLUMN_REVIEWER_ACTION: '',
  COLUMN_APPLICANT_ACTION: '',
  DECISION_LIST_OF_QUESTIONS: 'List Of Questions',
  DECISION_CHANGES_REQUESTED: 'Changes Requested',
  DECISION_CONFORM: 'Conform',
  DECISION_NON_CONFORM: 'Non-conform',
  DECISION_NO_DECISION: '',
  DATE_TODAY: 'Today',
  DATE_YESTERDAY: 'Yesterday',
  DATE_DAYS_AGO: 'days ago',
  DATE_LAST_WEEK: 'Last Week',
  DATE_WEEKS_AGO: 'weeks ago',
  DATE_LAST_MONTH: 'Last Month',
  DATE_MONTHS_AGO: 'months ago',
  DATE_LAST_YEAR: 'Last Year',
  DATE_YEARS_AGO: 'years ago',
  DEFAULT_TEMPLATE_CATEGORY_TITLE: 'General',
  DEFAULT_TEMPLATE_CATEGORY_ICON: 'globe',
  ERROR_APPLICATION_CREATE: 'Problem loading application creation page',
  ERROR_APPLICATION_DELETE: 'Problem deleting application',
  ERROR_APPLICATION_PAGE: 'Problem loading application',
  ERROR_APPLICATION_SUBMIT: 'Problem submitting application',
  ERROR_APPLICATIONS_LIST: 'Problem loading applications list',
  ERROR_FOUND: 'Errors found',
  ERROR_GENERIC: 'Something went wrong',
  ERROR_REVIEW_PAGE: 'Problem loading review',
  ERROR_LOGIN_PASSWORD: 'Oops! Problem with username or password',
  ERROR_STAGE_NOT_FOUND: 'Not Found',
  ERROR_LEVEL_NOT_FOUND: 'Level not found',
  ERROR_TRIGGER:
    'Problem waiting for triggers to finish. Please check console for detailed error info.',
  FILTER_ADD_FILTER: 'Filter',
  FILTER_START_TYPING: 'Start typing...',
  FILTER_REMOVE: 'Remove filter',
  FILTER_NAMED_DATE_TODAY: 'Today',
  FILTER_NAMED_DATE_YESTERDAY: 'Yesterday',
  FILTER_NAMED_DATE_THIS_WEEK: 'This Week',
  FILTER_NAMED_DATE_LAST_WEEK: 'Last Week',
  FILTER_NAMED_DATE_THIS_MONTH: 'This Month',
  FILTER_NAMED_DATE_LAST_MONTH: 'Last Month',
  FILTER_NAMED_DATE_NEXT_MONTH: 'Next Month',
  FILTER_NAMED_DATE_THIS_YEAR: 'This Year',
  FILTER_NAMED_DATE_LAST_YEAR: 'Last Year',
  FILTER_NAMED_DATE_NEXT_YEAR: 'Next Year',
  FILTER_LAST_ACTIVE: 'Last Active',
  FILTER_ASSIGNMENT_STATUS: 'Assignment Status',
  FILTER_ASSIGNMENT_STATUS_TRUE: 'Fully Assigned',
  FILTER_ASSIGNMENT_STATUS_FALSE: 'Not Fully Assigned',
  FILTER_APPLICANT_DEADLINE: 'Applicant Deadline',
  FILTER_STATUS: 'Status',
  FILTER_OUTCOME: 'Outcome',
  FILTER_STAGE: 'Stage',
  FILTER_ORGANISATION: 'Organisation',
  FILTER_APPLICANT: 'Applicant',
  FILTER_REVIEWER: 'Reviewer',
  FILTER_ASSIGNER: 'Assigner',
  FILTER_REVIEWER_ACTION: 'Reviewer Action',
  FILTER_ASSIGNER_ACTION: 'Assigner Action',
  FILTER_DATE_BEFORE: 'Before',
  FILTER_DATE_AFTER: 'After',
  FILTER_RESET_ALL: 'Reset all filters',
  FOOTER_TEXT: 'Powered by The mSupply Foundation',
  LABEL_APPLICATIONS: 'applications',
  LABEL_APPLICATION_SUBMITTED: 'Application Submitted',
  LABEL_APPLICATION_BACK: 'Back to form',
  LABEL_ASSIGNED_TO_YOU: 'Assigned to you',
  LABEL_ASSIGNED_TO_OTHER: 'Assigned to another reviewer',
  LABEL_ASSIGNMENT_LOCKED: 'Locked for',
  LABEL_ASSIGNMENT_SELF: 'Can be self assigned',
  LABEL_ASSIGNMENT_AVAILABLE: 'Can be self assigned by',
  LABEL_COMMENT: 'Add comment',
  LABEL_CONSOLIDATE: 'Consolidate',
  LABEL_CONSOLIDATION_AGREE: 'Agree',
  LABEL_CONSOLIDATION_DISAGREE: 'Disagree',
  LABEL_CONSOLIDATION_AGREEMENT: 'Agreed',
  LABEL_CONSOLIDATION_DISAGREEMENT: 'Disagreed',
  LABEL_DASHBOARD_NO_APPLICATIONS: "You don't have any applications in progress",
  LABEL_DASHBOARD_START_NEW: 'Start a new %1',
  LABEL_EXPORT: 'Export',
  LABEL_IMPORT: 'Import',
  LABEL_LIST_PER_PAGE: 'Applications per page',
  LABEL_LOADING: 'Loading...',
  LABEL_LOGIN_PASSWORD: 'Password',
  LABEL_LOGIN_USERNAME: 'Username',
  LABEL_LOG_IN: 'Log in',
  LABEL_FILE_IMPORT_CSV: 'Import CSV',
  LABEL_FILE_UPLOAD_TITLE: 'File input & upload',
  LABEL_FILE_UPLOAD: 'Choose a File',
  LABEL_FILE_UPLOAD_CHOSEN: 'File Chosen: ',
  LABEL_FILE_UPLOAD_PLACEHOLDER: 'Use the above bar to browse your file system',
  LABEL_FILE_DOWNLOAD_ERROR: 'Error trying to download',
  LABEL_NO_ORG: 'No organisation',
  LABEL_NO_ORG_SELECT: 'No organisation (act as user only)',
  LABEL_NO_ORG_OPTION: 'Log in without organisation',
  LABEL_PROCESSING: 'Processing...',
  LABEL_PREVIOUS_REVIEW: 'Previous review',
  LABEL_REVIEW: 'Application process',
  LABEL_REVIEW_APPROVE: 'Conform',
  LABEL_REVIEW_DECISION: 'Decision',
  LABEL_REVIEW_APPROVED: 'Approved',
  LABEL_REVIEW_DECLINED: 'Declined',
  LABEL_REVIEW_IN_PROGRESS: 'Review in Progress',
  LABEL_REVIEW_MAKE_DECISION_BY: 'Awaiting decision making by',
  LABEL_REVIEW_OVERALL_COMMENT: 'Overall comment',
  LABEL_REVIEW_OVERALL_COMMENT_TOOLTIP:
    '_If application outcome is_: \n- **Conform**: Please use this field to include a summary of the internal decision notes.\n- **Request information from the applicant**: Please use this field to include a summary of the internal decision notes. Note: Any non-conforming comments will be displayed to the applicant for actioning.\n- **Non-conform**: Please use this field to detail the reasons for rejection to the applicant.',
  LABEL_REVIEW_RESSUBMIT: 'Non conform',
  LABEL_REVIEW_SECTION: 'Please complete the section',
  LABEL_REVIEW_SUBMIT_AS: 'Submit as',
  LABEL_REVIEW_SUBMITTED_AS: 'Submitted as',
  LABEL_REVIEWER: 'Reviewer',
  LABEL_REASSIGN_TO: 'Reassign to',
  LABEL_UNASSIGN_FROM: 'Unassign from',
  LABEL_RESPONSE_UPDATE: 'Update',
  LABEL_RESPONSE_UPDATED: 'Updated',
  LABEL_SECTION_PROBLEM: 'Errors',
  LABEL_SECTION_COMPLETED: 'Completed',
  LABEL_SUBMITTING: 'Submitting...',
  LABEL_TRY_AGAIN: 'Try again',
  LABEL_VERIFICATION_FAILED: 'Verificaton Failed',
  LINK_NEW_ACCOUNT: 'Create new account',
  LINK_RESET_PASSWORD: 'Forgot my password',
  LOCALISATION_HEADER: 'Localisation',
  LOCALISATION_CURRENTLY_INSTALLED: 'Currently installed languages',
  LOCALISATION_DELETE_WARNING_TITLE: 'Are you sure?',
  LOCALISATION_DELETE_WARNING_MESSAGE: 'This will uninstall language %1 (%2) from your system',
  LOCALISATION_REMOVE_SUCCESS: '%1 (%2) successfully removed',
  LOCALISATION_REMOVE_ERROR: 'Error',
  LOCALISATION_REMOVE_PROBLEM: 'Problem removing lanuage',
  LOCALISATION_FILE_PROBLEM: 'Problem processing file',
  LOCALISATION_EXPORT_SUCCESS: 'Languages exported',
  LOCALISATION_EXPORT_SUCCESS_MESSAGE: 'CSV file has been downloaded',
  LOCALISATION_EXPORT_PROBLEM: 'There was a problem exporting languages',
  LOCALISATION_INSTALL_SUCCESS: 'Languages successfully installed',
  LOCALISATION_INCLUDE_DISABLED: 'Include disabled languages',
  LOCALISATION_NO_LANG_FOUND: 'No languages found in file',
  LOCALISATION_INSTALL_PROBLEM: 'Problem installing one or more languages',
  LOCALISATION_EXPORT_MESSAGE: 'Export languages as spreadsheet (CSV)',
  LOCALISATION_IMPORT_MESSAGE: 'Import languages from spreadsheet',
  LOGIN_WELCOME: 'Welcome, %1',
  LOGIN_ORG_SELECT: 'Please select an organisation',
  LOGIN_REDIRECT_TO_REGISTRATION: 'Re-directing to user registration application...',
  LOOKUP_ERROR_NOT_FOUND: 'No lookup-table found!',
  LOOKUP_ERROR_TITLE: 'Error loading lookup-table',
  LOOKUP_TABLE_HEADER_NAME: 'Name',
  LOOKUP_TABLE_HEADER_TABLE_NAME: 'Table Name',
  LOOKUP_TABLE_HEADER_ACTIONS: 'Actions',
  LOOKUP_TABLE_VIEW: 'View lookup table',
  LOOKUP_TABLE_IMPORT: 'Import lookup table',
  LOOKUP_TABLE_IMPORT_INTO: 'Import into Lookup-table:',
  LOOKUP_TABLE_IMPORT_OTHER: 'Import another CSV',
  LOOKUP_TABLE_DOWNLOAD: "Download '%1' table",
  LOOKUP_TABLE_FIELD_NAME: 'Database Field-name',
  LOOKUP_TABLE_LABEL: 'Lookup-table Label',
  LOOKUP_TABLE_NAME: 'Table name',
  LOOKUP_TABLE_ADD: 'Add new Lookup-table',
  LOOKUP_TABLE_TITLE: 'Lookup table:',
  LOOKUP_TABLE_CONTENTS: 'View individual lookup-table and its contents',
  LOOKUP_TABLE_SUBTITLE: 'This page contains the list of all lookup-tables',
  LOOKUP_TABLE_SUCCESS_CREATED: 'Lookup table %1 has been successfully created.',
  LOOKUP_TABLE_SUCCESS_UPDATED: 'Lookup table %1 has been successfully updated.',
  LOOKUP_TABLES_TITLE: 'Lookup Tables',
  MARKDOWN: 'Markdown',
  MARKDOWN_LINK: 'https://www.markdownguide.org/cheat-sheet/',
  MENU_ITEM_DASHBOARD: 'Dashboard',
  MENU_ITEM_APPLICATION_LIST: 'Application List',
  MENU_ITEM_DATA: 'Database',
  MENU_ITEM_MANAGE: 'Manage',
  MENU_ITEM_CONFIG: 'Configuration',
  MENU_ITEM_HELP: 'Help',
  MENU_ITEM_REF_DOCS: 'Reference',
  MENU_ITEM_ADMIN_TEMPLATES: 'Templates/Procedures',
  MENU_ITEM_ADMIN_LOOKUP_TABLES: 'Lookup Tables',
  MENU_ITEM_ADMIN_DATA_VIEW_CONFIG: 'Data View Configurations',
  MENU_ITEM_ADMIN_PERMISSIONS: 'Permission Policy & Names',
  MENU_ITEM_ADMIN_PLUGINS: 'Plugins',
  MENU_ITEM_ADMIN_LOCALISATION: 'Localisations',
  MENU_EDIT_USER: 'Edit User Details',
  MENU_CHANGE_LANGUAGE: 'Change Language',
  MENU_LANGUAGE_SELECT: 'Please select a language',
  MENU_LANGUAGE_CURRENT: 'current',
  MENU_LOGOUT: 'Log out',
  NO_MATCH_404_DEFAULT_HEADER: 'Something went wrong',
  NO_MATCH_404_DEFAULT_CONTENT: 'Page not found',
  NO_MATCH_404_GO_BACK: 'Go back',
  OPTION_OK: 'OK',
  OPTION_CANCEL: 'Cancel',
  OPTION_YES: 'Yes',
  OPTION_NO: 'No',
  OUTCOME_PENDING: 'In progress',
  OUTCOME_APPROVED: 'Approved',
  OUTCOME_REJECTED: 'Rejected',
  OUTCOME_EXPIRED: 'Expired',
  OUTCOME_WITHDRAWN: 'Withdrawn',
  OUTCOMES_TABLE_PAGINATION_TEXT: 'Items per page',
  PAGE: 'Page',
  PAGE_TITLE_HOME: 'Dashboard',
  PAGE_TITLE_LIST: 'Applications List',
  PAGE_TITLE_CREATE: 'New Application',
  PAGE_TITLE_APPLICATION: 'Application %1',
  PAGE_TITLE_REVIEW: 'Review %1',
  PAGE_TITLE_TEMPLATES: 'Templates',
  PAGE_TITLE_LOOKUP_TABLES: 'Lookup Tables',
  PAGE_TITLE_DATA_VIEW: 'Data Views',
  PAGE_TITLE_LOCALISATION: 'Localisations',
  PAGE_TITLE_PLUGINS: 'Plug-ins',
  PAGE_TITLE_PERMISSIONS: 'Permissions',
  PLACEHOLDER_SEARCH: 'Search Applications...',
  REVIEW_OVERVIEW_ACTIVITY: 'Activity',
  REVIEW_OVERVIEW_APPLICANT: 'Applicant',
  REVIEW_OVERVIEW_ORG: 'Organisation',
  REVIEW_OVERVIEW_STARTED: 'Started',
  REVIEW_OVERVIEW_COMPLETED: 'Completed',
  REVIEW_OVERVIEW_STAGE: 'Stage',
  REVIEW_OVERVIEW_OUTCOME: 'Outcome',
  REVIEW_OVERVIEW_SERIAL: 'Serial',
  REVIEW_OVERVIEW_DEADLINE: 'Applicant Deadline',
  REVIEW_OVERVIEW_EXTEND_BY: 'Extend deadline by',
  REVIEW_OVERVIEW_DAYS: 'days',
  REVIEW_OVERVIEW_DAYS_SINGULAR: 'day',
  REVIEW_OVERVIEW_MODAL_MESSAGE: "This will extend the applicant's deadline by %1 days",
  REVIEW_OVERVIEW_MODAL_MESSAGE_SINGULAR: "This will extend the applicant's deadline by one day",
  REVIEW_OVERVIEW_BUTTON_EXTEND: 'Extend',
  REVIEW_PROGRESS_BAR_SUBMITTED: 'Submitted',
  REVIEW_SUBMISSION_CONFIRM_TITLE: 'Submitting Review',
  REVIEW_SUBMISSION_CONFIRM_MESSAGE:
    'You are about to submit your review. Are you sure you wish to proceed?',
  REVIEW_SUBMISSION_CONFIRM_OPTION: 'Submitting Review',
  REVIEW_SUBMISSION_FAIL: 'Not all sections have been reviewed',
  REVIEW_SUBMISSION_ERROR: 'Something wrong with server - review mutation failed',
  REVIEW_DECISION_PREVIEW_NOTHING_SELECTED_TITLE: 'No decision selected',
  REVIEW_DECISION_PREVIEW_NOTHING_SELECTED_TEXT:
    'You must select a decision before you can preview the output',
  REVIEW_DECISION_PREVIEW_HEADER: 'Preview Decision Documentation',
  REVIEW_DECISION_PREVIEW_TEXT:
    'Here is a preview of documents and correspondence that will be sent to the applicant as a result of the decision:',
  REVIEW_DECISION_PREVIEW_FETCHING: 'Fetching previews...',
  REVIEW_DECISION_PREVIEW_ERROR_HEADER: 'Something went wrong',
  REVIEW_DECISION_PREVIEW_ERROR_TEXT: 'There was a problem generating previews',
  REVIEW_DECISION_NO_PREVIEWS_AVAILABLE: 'No previews available',
  REVIEW_PREVIEW_NOTIFICATION: 'Email message:',
  REVIEW_PREVIEW_ERROR: 'Problem generating preview:',
  REVIEW_DECISION_SET_FAIL_TITLE: 'Problem submitting review',
  REVIEW_DECISION_SET_FAIL_MESSAGE: 'Please select a decision: List Of Questions or Non Conformity',
  REVIEW_DECISION_MISMATCH_TITLE: 'Final decision',
  REVIEW_DECISION_MISMATCH_MESSAGE:
    'You have made a different decision than the previous reviewer.\nAre you sure you wish to proceed with your decision?',
  REVIEW_STATUS_PENDING_TITLE: 'Please reload review before submitting',
  REVIEW_STATUS_PENDING_MESSAGE:
    'All your existing decisions will be kept.\nYou will be redirected to the home page now. Click "Start" in there to reload page with latest responses to review.',
  REVIEW_STATUS_IN_PROGRESS: 'In progress',
  REVIEW_STATUS_NOT_STARTED: 'Not started',
  REVIEW_STATUS_PENDING_ACTION: 'Pending reviewer action',
  REVIEW_IN_PROGRESS_BY: 'Review in progress by',
  REVIEW_DONE_BY: 'Review submitted by',
  CONSOLIDATION_IN_PROGRESS_BY: 'Consolidation by',
  CONSOLIDATION_DONE_BY: 'Consolidation submitted by',
  REVIEW_NOT_FOUND: 'Not found',
  REVIEW_NOT_READY: 'Not ready to review',
  REVIEW_STARTED: 'Review started',
  REVIEW_SUBMITTED_BY: 'Review submitted by',
  REVIEW_FILTER_ALL_LEVELS: 'All levels',
  REVIEW_FILTER_LEVEL: 'Level',
  REVIEW_FILTER_SHOW_TASKS_FOR: 'Show tasks for',
  REVIEW_TAB_OVERVIEW: 'Overview',
  REVIEW_TAB_ASSIGNMENT: 'Assignment',
  REVIEW_TAB_SUMMARY: 'Summary',
  REVIEW_TAB_NOTES: 'Internal Notes',
  REVIEW_TAB_DOCUMENTS: 'Documents',
  REVIEW_DOC_HEADER: 'Documents generated by this application',
  REVIEW_NOTES_SORT_ORDER: 'Sort order:',
  REVIEW_NOTES_FILES_ONLY: 'Files only',
  REVIEW_NOTES_NEW_NOTE: 'Add note',
  REVIEW_NOTES_SUBMIT_MSG: 'Submitting note...',
  REVIEW_NOTES_UPLOADING_MSG: 'Uploading files...',
  REVIEW_NOTES_DELETING_MSG: 'Deleting note...',
  REVIEW_NOTES_MUTATION_ERROR: 'Problem modifying note. See console for details.',
  REVIEW_NOTES_NEWEST_FIRST: 'Newest first',
  REVIEW_NOTES_OLDEST_FIRST: 'Oldest first',
  REVIEW_NOTES_NO_NOTES: 'No notes on this application yet',
  REVIEW_NOTES_COMMENT_ERROR: 'You need a comment',
  REVIEW_NOTES_ENTER_COMMENT: 'Enter comment',
  REVIEW_NOTES_MARKDOWN_SUPPORT: '(Markdown formatting is supported)',
  REVIEW_NOTES_ADD_FILES: 'Add files',
  REVIEW_NOTES_FILES: 'Files',
  REVIEW_NOTES_HOVER_TO_REMOVE: '(Hover to remove)',
  REVIEW_NOTES_DELETE_TITLE: 'Are you sure?',
  REVIEW_NOTES_DELETE_MESSAGE:
    'Clicking "Confirm" will permanently delete your comment, including any associated files. Close this dialog to go back.',
  STATUS_SUBMITTED: 'Submitted',
  STATUS_DRAFT: 'Draft',
  STATUS_CHANGES_REQUIRED: 'Changes required',
  STATUS_RE_SUBMITTED: 'Re-submitted',
  STATUS_COMPLETED: 'Completed',
  SUBTITLE_APPLICATION_STEPS:
    'The following steps will need to be completed before the form can be submitted',
  SUBTITLE_APPLICATION_CHANGES_REQUIRED:
    'There are issues with some of the information you supplied. Please update and resubmit the form.',
  SUBTITLE_APPLICATION_SUMMARY: 'Please review each section before submitting form',
  SUBTITLE_REVIEW: 'Please complete the sections that have been assigned to you',
  SUBTITLE_SUBMISSION_STEPS: 'Stages for this application:',
  TEMPLATE_APPEARS_IN: 'Appears in',
  TEMPLATE_BUTTON_ADD: 'Add',
  TEMPLATE_BUTTON_ADD_ACTION: 'Add Action',
  TEMPLATE_BUTTON_ADD_CATEGORY: 'Add Category',
  TEMPLATE_BUTTON_EDIT_CATEGORY: 'Edit Category',
  TEMPLATE_CATEGORIES: 'Categories',
  TEMPLATE_CODE: 'Code',
  TEMPLATE_GEN_BUTTON_AVAILABLE: 'Make Available',
  TEMPLATE_GEN_BUTTON_AVAILABLE_DISABLED:
    'At least one template with the same code is already available, or this template already available',
  TEMPLATE_GEN_BUTTON_DRAFT: 'Make Draft',
  TEMPLATE_GEN_BUTTON_DRAFT_DISABLED: 'Already has appications or is draft',
  TEMPLATE_GEN_BUTTON_DISABLE: 'Disable',
  TEMPLATE_GEN_BUTTON_DISABLE_DISABLED: 'Already disabled',
  TEMPLATE_ICON: 'Icon',
  TEMPLATE_LABEL_ACTION: 'Action',
  TEMPLATE_LABEL_ACTION_DESCRIPTION: 'new action description',
  TEMPLATE_LABEL_ACTION_MESSAGE: 'new action message',
  TEMPLATE_LABEL_ACTION_ON_TOP: 'Add on top',
  TEMPLATE_LABEL_DESCRIPTION: 'Description',
  TEMPLATE_LABEL_CONDITION: 'Condition',
  TEMPLATE_LABEL_SEQUENTIAL: 'Is Sequential',
  TEMPLATE_MESSAGE_SAVE_AND_CLOSE: 'There are changes not saved. Would you like to save and close?',
  TEMPLATE_MESSAGE_SAVE_SUCCESS: 'Changes saved',
  TEMPLATE_MESSAGE_SAVE_DISABLED: 'No changes',
  TEMPLATE_MESSAGE_REMOVE_ELEMENT_TITLE: 'Remove element',
  TEMPLATE_MESSAGE_REMOVE_ELEMENT_CONTENT: 'Are you sure you would like to remove this element?',
  TEMPLATE_NEW_CODE: 'New code',
  TEMPLATE_NEW_TITLE: 'New title',
  TEMPLATE_NO_CATEGORY: 'No category',
  TEMPLATE_TITLE: 'Title',
  TEMPLATE_UI_ADMIN: 'Admin menu',
  TEMPLATE_UI_MANAGE: 'Management menu',
  TEMPLATE_UI_DASHBOARD: 'Dashboard',
  TEMPLATE_UI_MENU: 'Application List menu',
  TEMPLATE_UI_USER: 'User menu',
  TIMELINE_NO_ACTIVITY: 'Moved to stage -- no activity yet',
  TIMELINE_APPLICATION_STARTED: 'Application started',
  TIMELINE_APPLICATION_RESTARTED: 'Application restarted',
  TIMELINE_APPLICATION_SUBMITTED: 'Application submitted',
  TIMELINE_APPLICATION_RESUBMITTED: 'Application re-submitted after making changes',
  TIMELINE_APPLICATION_EXPIRED: '⌛ Application expired',
  TIMELINE_APPLICATION_WITHDRAWN: 'Application withdrawn',
  TIMELINE_APPLICATION_APPROVED: '✅ Application **approved**',
  TIMELINE_APPLICATION_REJECTED: '❌ Application has been **rejected**',
  TIMELINE_DEADLINE_EXTENDED: '%1 extended the deadline to:',
  TIMELINE_WAITING_FOR_APPLICANT: 'Waiting for applicant to make changes',
  TIMELINE_WAITING_FOR_REVIEWER: 'Waiting for reviewer %1 to make changes',
  TIMELINE_REVIEW_ASSIGNED: 'Reviewer %1 was assigned %2 by %3',
  TIMELINE_REVIEW_SELF_ASSIGNED: 'Reviewer %1 was assigned to %2 by self-assignment',
  TIMELINE_UNASSIGNED: 'Reviewer %1 was unassigned from %2 by %3',
  TIMELINE_CONSOLIDATION_ASSIGNED: '%1 was assigned to consolidate %2 by %3',
  TIMELINE_CONSOLIDATION_SELF_ASSIGNED: '%1 was assigned to consolidate %2 by self-assignment',
  // Used for matching in subesquent URL replacements
  TIMELINE_REVIEW: 'review',
  TIMELINE_CONSOLIDATION: 'consolidation',
  TIMELINE_REVIEW_DISCONTINUED: "%1's review was discontinued",
  TIMELINE_REVIEW_STARTED: '%1 started their review',
  TIMELINE_REVIEW_RESTARTED: '%1 restarted their review',
  TIMELINE_REVIEW_SUBMITTED: '%1 submitted their review',
  TIMELINE_REVIEW_SUBMITTED_DECISION: '%1 submitted their review with the decision %2',
  TIMELINE_REVIEW_RESUBMITTED: '%1 re-submitted their review',
  TIMELINE_REVIEW_RESUBMITTED_DECISION: '%1 re-submitted their review with the decision %2',
  TIMELINE_CONSOLIDATION_STARTED: '%1 started their consolidation',
  TIMELINE_CONSOLIDATION_RESTARTED: '%1 restarted their consolidation',
  TIMELINE_CONSOLIDATION_SUBMITTED: '%1 submitted their consolidation',
  TIMELINE_CONSOLIDATION_SUBMITTED_DECISION:
    '%1 submitted their consolidation with the decision %2',
  TIMELINE_CONSOLIDATION_RESUBMITTED: '%1 re-submitted their consolidation',
  TIMELINE_CONSOLIDATION_RESUBMITTED_DECISION:
    '%1 re-submitted their consolidation with the decision %2',
  TIMELINE_ERROR_MESSAGE: 'Problem parsing this event -- See console for details',
  TIMELINE_SECTIONS: 'Sections',
  TIMELINE_COMMENT: 'Comment:',
  TIMELINE_ALL_SECTIONS: 'All sections',
  TITLE_HISTORY_CHANGED_BY_APPLICANT: 'Changed by applicant',
  TITLE_HISTORY_CONSOLIDATION: 'Consolidation',
  TITLE_HISTORY_REVIEW: 'Review',
  TITLE_HISTORY_SUBMITTED_BY_APPLICANT: 'Submitted by applicant',
  TITLE_HISTORY_PANEL: 'Review History',
  TITLE_LOGIN_HEADER: 'Application Manager',
  TITLE_LOGIN: 'Login',
  TITLE_APPLICATION_FORM: 'application form',
  TITLE_APPLICATION_SUMMARY: 'Review and Submit',
  TITLE_APPLICATION_SUBMITTED: 'Submitted application',
  TITLE_DETAILS: 'Details',
  TITLE_INTRODUCTION: 'Introduction',
  TITLE_REVIEW_COMMENT: 'Overall comment',
  TITLE_REVIEW_DECISION: 'Submitted decision',
  TITLE_REVIEW_SUMMARY: 'Review Summary',
  TITLE_STEPS: 'Steps to complete',
  TITLE_OVERVIEW: 'Overview',
  UNASSIGN_TITLE: 'Unassignment of reviewer',
  UNASSIGN_MESSAGE: 'Are you sure you would like to un-assign?',
  VALIDATION_REQUIRED_ERROR: 'Field is required',
}
