enum APPLICATION_COLUMN {
  LAST_ACTIVE_DATE = 'LAST_ACTIVE_DATE',
  DEADLINE_DATE = 'DEADLINE_DATE',
  APPLICATION_NAME = 'APPLICATION_NAME',
  APPLICANT = 'APPLICANT',
  COMPANY = 'COMPANY',
  CONSOLIDATOR = 'CONSOLIDATOR',
  STAGE = 'STAGE',
  STATUS = 'STATUS',
  ACTIONABLE = 'ACTIONABLE',
}

export default APPLICATION_COLUMN
