import { ColumnsPerRole } from '../../utils/types'
import APPLICATION_COLUMN from './applicationColumn'

const COLUMNS_PER_ROLE: ColumnsPerRole = {
  applicant: [
    APPLICATION_COLUMN.LAST_ACTIVE_DATE,
    APPLICATION_COLUMN.DEADLINE_DATE,
    APPLICATION_COLUMN.APPLICATION_NAME,
    APPLICATION_COLUMN.STAGE,
    APPLICATION_COLUMN.STATUS,
    APPLICATION_COLUMN.OUTCOME,
  ],
  reviewer1: [
    APPLICATION_COLUMN.LAST_ACTIVE_DATE,
    APPLICATION_COLUMN.APPLICATION_NAME,
    APPLICATION_COLUMN.APPLICANT,
    APPLICATION_COLUMN.ORGANISATION,
    APPLICATION_COLUMN.CONSOLIDATOR,
    APPLICATION_COLUMN.STAGE,
    APPLICATION_COLUMN.STATUS,
    APPLICATION_COLUMN.OUTCOME,
  ],
  reviewer2: [
    APPLICATION_COLUMN.LAST_ACTIVE_DATE,
    APPLICATION_COLUMN.APPLICATION_NAME,
    APPLICATION_COLUMN.APPLICANT,
    APPLICATION_COLUMN.ORGANISATION,
    APPLICATION_COLUMN.CONSOLIDATOR,
    APPLICATION_COLUMN.STAGE,
    APPLICATION_COLUMN.STATUS,
    APPLICATION_COLUMN.OUTCOME,
  ],
  supervisor: [
    APPLICATION_COLUMN.LAST_ACTIVE_DATE,
    APPLICATION_COLUMN.APPLICATION_NAME,
    APPLICATION_COLUMN.APPLICANT,
    APPLICATION_COLUMN.ORGANISATION,
    APPLICATION_COLUMN.STATUS,
    APPLICATION_COLUMN.OUTCOME,
  ],
  consolidator: [
    APPLICATION_COLUMN.LAST_ACTIVE_DATE,
    APPLICATION_COLUMN.APPLICATION_NAME,
    APPLICATION_COLUMN.APPLICANT,
    APPLICATION_COLUMN.ORGANISATION,
    APPLICATION_COLUMN.STATUS,
    APPLICATION_COLUMN.OUTCOME,
  ],
}

export default COLUMNS_PER_ROLE
