# On every push this script is executed
on:
  push:
    branches:
      - main
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: shalzz/zola-deploy-action
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: docs/public
          TOKEN: ${{ secrets.ZOLAGENERATEDOCS }}